// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComLKarlonHttpRestApiGitApiModels(in *jlexer.Lexer, out *INNInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fam":
			out.Fam = string(in.String())
		case "nam":
			out.Nam = string(in.String())
		case "otch":
			out.Otch = string(in.String())
		case "bdate":
			out.Bdate = string(in.String())
		case "doctype":
			out.Doctype = string(in.String())
		case "docno":
			out.Docno = string(in.String())
		case "c":
			out.C = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComLKarlonHttpRestApiGitApiModels(out *jwriter.Writer, in INNInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fam\":"
		out.RawString(prefix[1:])
		out.String(string(in.Fam))
	}
	{
		const prefix string = ",\"nam\":"
		out.RawString(prefix)
		out.String(string(in.Nam))
	}
	{
		const prefix string = ",\"otch\":"
		out.RawString(prefix)
		out.String(string(in.Otch))
	}
	{
		const prefix string = ",\"bdate\":"
		out.RawString(prefix)
		out.String(string(in.Bdate))
	}
	{
		const prefix string = ",\"doctype\":"
		out.RawString(prefix)
		out.String(string(in.Doctype))
	}
	{
		const prefix string = ",\"docno\":"
		out.RawString(prefix)
		out.String(string(in.Docno))
	}
	{
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.String(string(in.C))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v INNInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComLKarlonHttpRestApiGitApiModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v INNInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComLKarlonHttpRestApiGitApiModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *INNInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComLKarlonHttpRestApiGitApiModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *INNInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComLKarlonHttpRestApiGitApiModels(l, v)
}
